spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/alotutienda}
    username: ${DB_USER:easymanager}
    password: ${DB_PASS:Easy1234.}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    generate-ddl: true
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  server:
    compression:
      enabled: trueW
    servlet:
      context-path: /easymanager

  security:
    user:
      name: test
      password: test

  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
    url: ${DB_URL:jdbc:postgresql://localhost:5432/alotutienda}
    user: ${DB_USER:easymanager}
    password: ${DB_PASS:Easy1234.}
    enabled: ${LIQUIBASE_ENABLED:true}
    parameters.dbms: ${DB_PLATFORM:postgresql}
