server:
  servlet:
    context-path: /easymanager
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: tour-api
  messages:
    basename: bundles/apiLanguageBundle
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  liquibase :
    change-log: classpath:db.changelog/changelog-master.xml
    url:



