INSERT INTO PRODUCT
(ID,BASE_QUANTITY,BRAND,CATEGORY,CODE,CREATE_DATE,DESCRIPTION,NAME,PRIVATE_PRICE,PUBLIC_PRICE,STOCK,UPDATE_DATE)
VALUES (99,101,'PRUEBA','SINCATEGORIA','ABC123',SYSDATE,'PRUEBA DE INSERCION','PRUEBANAME',12000,2500,200,SYSDATE);
